version: '3.4'

services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./:/app
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: php.Dockerfile
    volumes:
      - ./:/app
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
